# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beverage_name', models.CharField(max_length=200)),
                ('beverage_description', models.CharField(max_length=1000)),
                ('create_datetime', models.DateTimeField(verbose_name='datetime created')),
            ],
        ),
        migrations.CreateModel(
            name='Fermentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fermentation_start_date', models.DateTimeField(verbose_name='datetime started')),
                ('fermentation_end_date', models.DateTimeField(verbose_name='datetime ended')),
                ('fermentation_original_gravity', models.DecimalField(decimal_places=3, max_digits=4)),
                ('fermentation_final_gravity', models.DecimalField(decimal_places=3, max_digits=4)),
                ('fermentation_final_abv', models.DecimalField(decimal_places=2, max_digits=4)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.Beverage')),
            ],
        ),
        migrations.CreateModel(
            name='FermentationProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateTimeField(verbose_name='datetime measured')),
                ('specific_gravity', models.DecimalField(decimal_places=3, max_digits=4)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fermentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.Fermentation')),
            ],
        ),
    ]
