# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='beverage_beersmith_ref',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
